apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cps-pack-parser
  labels:
    app: cps-pack-parser
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cps-pack-parser-app
  template:
    metadata:
      labels:
        app: cps-pack-parser-app
    spec:
      containers:
        - name: cps-pack-parser
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/probation-services/cps-pack-parser:1.1
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
            requests:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: '8000'
