apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cps-pack-parser-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - cps-pack-parser.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
    - host: cps-pack-parser.apps.live-1.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: cps-pack-parser-service
              servicePort: 8000
